version: '3'
services:
  frontend:
    build: ./
    restart: always
    container_name: frontend_vacobulary
    ports:
      - 3010:3000
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx_vacobulary
    ports:
      - 3020:80
networks:
  default:
    external:
      name: test